### ISSUE TITLE
Duplicate key 'extends' 

### ISSUE THREAD

**Issue by capegreg** [Code-Pop/Real-World-Vue-3-TypeScript#1]
out of the box code gets this error

$ npm run lint

> vue-3-and-typescript@0.1.0 lint
> vue-cli-service lint

error: Duplicate key 'extends' (no-dupe-keys) at .eslintrc.js:26:3:
  24 |   },
  25 |
> 26 |   extends: [
     |   ^
  27 |     "plugin:vue/vue3-essential",
  28 |     "eslint:recommended",
  29 |     "@vue/typescript/recommended",

**Comment by bencodezen** [comment]
Hey @capegreg. Sorry for the delay in responding. It looks like this may be fixed at this point. So I'm going to close it, but let me know if you run into this again!
